### ISSUE TITLE
npm install dropbox doesn't work

### ISSUE THREAD

**Issue by smurthas** [evnm/dropbox-node#12]
when installing with npm, the only files copied into the node_modules/dropbox dir are:

```
LICENSE
README.md
index.js
node_modules
package.json
specs.js
```

Notably, the lib dir is missing, which results in:

```
Error: Cannot find module './lib/dropbox-node'
    at Function._resolveFilename (module.js:322:11)
    at Function._load (module.js:267:25)
    at require (module.js:351:19)
    at Object.<anonymous> (/Users/Simon/dev/tmp/node_modules/dropbox/index.js:1:80)
```

I'm on node v0.4.8 and npm v1.0.10

**Comment by evnm** [comment]
A fresh `npm install dropbox` works just fine for me, aside from a warning about a deprecated package.json field, which I subsequently resolved. I'm also running node v0.4.8 and npm v1.0.10.

What platform are you running on? Are you using nvm or any other node-/npm-related tools?

**Comment by smurthas** [comment]
I cleaned out my install of node, npm, and nvm and now things seem to work. Strange error, not sure what it was, but seems likely that it was on my end!
