### ISSUE TITLE
API consistency

### ISSUE THREAD

**Issue by nils-werner** [evnm/dropbox-node#13]
I've noticed that the API your module is providing is a bit inconsistent:
- `putFile` only accepts the path to a file that you want to upload whereas `getFile` simply returns a string
- there is a a `getFileStream` method but no `putFileStream` equivalent (already being worked on in #11)

My suggestion is to add two methods to this module:
- `putFile` and `getFile`, both accept a path on the local and the remote system and transfer the data using buffers
- `putString` and `getString`, accepting/returning a string
- `putFileStream` and `getFileStream` accepting/returning a stream

**Comment by nils-werner** [comment]
I will try to put together a pullrequest once I've familiarised myself more with node.js and dropbox-node :-)

**Comment by evnm** [comment]
Closing this issue, as this library has long been deprecated.
