### ISSUE TITLE
Official support for web apps

### ISSUE THREAD

**Issue by mark-hahn** [evnm/dropbox-node#17]
The README says ...

"The current Dropbox API is targeted for mobile applications, and thus web apps using it aren't "officially supported."

However, this page: http://forums.dropbox.com/topic.php?id=41097&replies=4 says ...

"A quick note for desktop developers looking into the Dropbox API: we aren't yet officially supporting desktop applications. We've been focusing our efforts on improving the API for mobile and web apps". 

So you might consider changing the README to reflect this.

**Comment by evnm** [comment]
I smell a misprint. On the web app API documentation site, it still says that [web applications using the Dropbox API are currently not officially supported](https://www.dropbox.com/developers/web_docs). However, I'm going to go by the forum post and [remove the disclaimer](https://github.com/evnm/dropbox-node/commit/af95ab910c). Thanks for filing the issue.
