### ISSUE TITLE
getFile does not work for filenames with parentheses

### ISSUE THREAD

**Issue by jtsao22** [evnm/dropbox-node#18]
Hey Evan, thanks a lot for this dropbox node code. It saved me so much time! 

Anyway, when I tried getFile'ing a file with parentheses (e.g. Fade Into Darkness (Vocal Club Mix).mp3), dropbox returned with an invalid signature error. I fixed this by using the escape function instead of the encodeURIComponent in the util/escape-path.js file:

module.exports = function escapePath(p) {
    return escape(p).replace(/%2F/g, '/');
}

Thanks again!

**Comment by evnm** [comment]
Fixed in [e11704880](https://github.com/evnm/dropbox-node/commit/e11704880c5). Thanks for the heads-up!
