### ISSUE TITLE
TypeError: Object #<Object> has no method 'getMetadata'

### ISSUE THREAD

**Issue by abhisri** [evnm/dropbox-node#19]
I am new to nodejs. Had checked out the latest code and was trying the demo.
On submitting the login form I am getting the following message.

TypeError: Object #<Object> has no method 'getMetadata'
    at Router.<anonymous> (/root/dropbox-node/examples/db-browser/app.js:48:20)

Here are the versions of the libraries involved.

root@pc:~# npm list
/root
├─┬ connect@1.6.2 
│ ├── mime@1.2.2 
│ └── qs@0.3.0 
├─┬ express@2.4.4 
│ ├── connect@1.6.2 
│ ├── mime@1.2.2 
│ └── qs@0.3.0 
├── jade@0.14.2 
└── oauth@0.9.5 

root@pc:~/dropbox-node# npm ls
dropbox@0.3.2 /root/dropbox-node
└── oauth@0.9.5 

Contents of req.db.session after the call to getAccesstoken(using the app key and secret, I generated and copy pasted) are as follows :

{ consumer_key: 'notshowingmygeneratedkey',
  consumer_secret: 'notshowingmygeneratedseret',
  access_token: undefined,
  access_token_secret: undefined,
  oauth: 
   { _isEcho: false,
     _requestUrl: 'http://api.dropbox.com/0/oauth/request_token',
     _accessUrl: 'http://api.dropbox.com/0/oauth/access_token',
     _consumerKey: 'notshowingmygeneratedkey',
     _consumerSecret: 'notshowingmygeneratedseret',
     _version: '1.0',
     _authorize_callback: null,
     _signatureMethod: 'HMAC-SHA1',
     _nonceSize: 32,
     _headers: 
      { Accept: '_/_',
        Connection: 'close',
        'User-Agent': 'Node authentication' },
     _defaultClientOptions: 
      { requestTokenHttpMethod: 'POST',
        accessTokenHttpMethod: 'POST' },
     _clientOptions: 
      { requestTokenHttpMethod: 'POST',
        accessTokenHttpMethod: 'POST' } } }

The email id/password used works on the dropbox site. Don't seem to be getting an access token nevertheless? what am I missing?

**Comment by evnm** [comment]
Thanks for filing an issue. I've gotten a lot of complaints about this, so will be looking into it soon. I believe it has to do with Connect changing out from under dropbox-node.

**Comment by evnm** [comment]
Fixed in [126b75df477](https://github.com/evnm/dropbox-node/commit/126b75df477a4fae7e7ef65ab92fcac1e3d49c90). Please reopen this issue if it still doesn't work for you.

**Comment by abhisri** [comment]
Works perfectly now! Thank you so much for the quick resolution.
