### ISSUE TITLE
Implement access token acquisition

### ISSUE THREAD

**Issue by thiloplanz** [evnm/dropbox-node#2]
Would be nice to be able to use the official API to transform a user's password into an access token pair.

**Comment by evnm** [comment]
Thanks for bringing this up. It's a valid improvement and I needed to be poked before getting to it.

I've refactored dropbox-node a bit in [a separate branch](https://github.com/evnm/dropbox-node/tree/internal-auth). Not only are access token pairs fetched internally via the Dropbox API, but I simplified the overall semantics a bit. With this change, the OAuth upkeep is handled internally and you must call an `init` function before interacting with any Dropbox API methods.

Thus, the DropboxClient constructor just takes the consumer key and secret, and the user's email and password are passed to `init`:

```
var dropbox = new DropboxClient(consumer_key, consumer_secret)

dropbox.init(email, password, function(err) {
  if (err) return console.error('Error: ' + sys.inspect(err))
  dropbox.deleteItem('foo', function(err, data) {
    if (err) console.error('Error: ' + sys.inspect(err))
    else console.log(sys.inspect(data))
  })
})
```

I'll mull this over and remain open to feedback/ideas before merging into master.

**Comment by thiloplanz** [comment]
Is there also a different version of "init" that can take the token pair instead of email and password? Because users of the API are not supposed to store the password or use it for more than the initial setup. I think I have read in the Dropbox API docs that they will shut you down if you keep calling /token all over.

**Comment by evnm** [comment]
Hmm... good point. Storing the password wouldn't necessarily be an issue, because you could pass the user's credential's to init directly. However, we definitely want to keep the access token/secret pair around after initially fetching it.

What if the call to /token within init is predicated on whether or not the key pair is defined? In this case, if you've already fetched the key pair, it would just fire the callback without hitting /token.

Example [here](https://github.com/evnm/dropbox-node/commit/d48809e).

**Comment by thiloplanz** [comment]
Yes that would work.

Since the token acquisition is supposed to be a rare operation, and authentication is important enough to warrant explicit method calls rather than "clever defaults", I'd prefer the following API, though :

```
 var dropbox = new DropboxClient( ....);
 // if you still need to do that (i.e. your application does not have the token)
 dropbox.getAccessToken( email, password, function (token) {} );
// (no need to init() for this method, does not change the internal state of the instance)
// returns { accessToken: x, accessTokenSecret: y, email: email }

// and after that 

dropbox.init(tokens, callback); // in the above form, email is optional
// or
dropbox.init( accessToken, accessTokenSecret, callback);
```

(Having to write getAccessToken with a callback to receive the results does make this a little unwieldy.... But since you should almost never need to do that, and you also probably want to have an easy entry point to control how you save the resulting token, it is probably still better to keep it explicit, rather than hiding it away inside of the client object).

**Comment by evnm** [comment]
I can see how this would be beneficial when a user wants access to their key pair, but it seems to me that in these situations you'd end up nesting init within a call to getAccessToken:

```
dropbox.getAccessToken(email, pwd, function (token, secret) {
  dropbox.init({token: token, secret: secret}, function (err) {...})
})
```

Correct me if I'm wrong, but I'm assuming that in your example, the two final calls to dropbox.init aren't meant to be inline (because at that point in the code you wouldn't have access to the token).

**Comment by thiloplanz** [comment]
> Correct me if I'm wrong, but I'm assuming that in your example, the two final calls to dropbox.init aren't meant to be inline (because at that point in the code you wouldn't have access to the token).

They are not inline, but they are not supposed to be in a callback, either. They will usually be in a completely separate action/page (request in HTTP terms).

The flow I believe the Dropbox API guidelines suggest is that there is a setup page where the user enters his password. This will call `getAccessToken`, store the token somewhere (client or server) and report success to the user. After that, the UI will show the account as active and allow operations like `getFile`. Those operations will not need to have access to the password and work with the access token.

The API should be geared towards this two-step process, where token management is explicitly left to the application.

Supporting implicit authentication using passwords by methods like `getFile` could be an option, but I would not want to use it, because this approach might get my account suspended.

**Comment by evnm** [comment]
That general scheme (having a setup function that initially fetches the key pair and only then using the other methods to make API calls) is more or less what I've had in mind. It's very conducive to binding each set of methods to certain routes within a web app, for example.

This functionality is supported with [this commit](https://github.com/evnm/dropbox-node/commit/0cf953d). I could also allow clients to specify a token/secret pair within the `optargs` object passed into each API method This would allow calls to be made directly in cases where the client already has a key pair for some reason.

**Comment by thiloplanz** [comment]
That looks good now, thanks. (Have you thought about that Flattr button?)

**Comment by evnm** [comment]
Heh, knowing that this lib is attracting interest and being used is payment enough. Thanks, though.
