### ISSUE TITLE
Dropbox API v1 support

### ISSUE THREAD

**Issue by podviaznikov** [evnm/dropbox-node#22]
Dropbox updated their API.

https://www.dropbox.com/developers/announcements/11

Library should support it. 

Currently example application just doesn't work because of the error: "You're using an older version of the Dropbox API with a new API key. Please use the latest version."

**Comment by fb55** [comment]
+1

**Comment by sreuter** [comment]
+1

**Comment by evnm** [comment]
Thanks for the issue. I realize this is a must-have, but will be short on time for the next week or so. I'll try to get to it over the Christmas holiday.

**Comment by svnlto** [comment]
+1

**Comment by evnm** [comment]
Closing this issue, as this library has long been deprecated.
