### ISSUE TITLE
npm warning on package.json

### ISSUE THREAD

**Issue by sreuter** [evnm/dropbox-node#23]
using latest node + npm outputs the following:

npm WARN express-extras@0.1.0 package.json: bugs['web'] should probably be bugs['url']

**Comment by evnm** [comment]
What are you doing to see this output? `npm install dropbox` in an empty directory doesn't give any warnings for me.

**Comment by evnm** [comment]
Closing this on account of not being able to reproduce it.

**Comment by fb55** [comment]
The package `express-extras` isn't part of this package. Wrong project, anyway (reopen it at the repo of `express-extras`).
