### ISSUE TITLE
dropbox-node: permission problem

### ISSUE THREAD

**Issue by thienit5** [evnm/dropbox-node#27]
i'm new dropbox developer, i'm try to run examples/db-browser/app.js but get some error:

This is dropbox i show:

{ consumer_key: 'c3i9jy0hnxlxm4t',
  consumer_secret: 'cxmupkxtmh0ga1b',
  access_token: undefined,
  access_token_secret: undefined,
  oauth:
   { _isEcho: false,
     _requestUrl: 'https://api.dropbox.com/1/oauth/request_token',
     _accessUrl: 'https://api.dropbox.com/1/oauth/access_token',
     _consumerKey: 'c3i9jy0hnxlxm4t',
     _consumerSecret: 'cxmupkxtmh0ga1b',
     _version: '1.0',
     _authorize_callback: null,
     _signatureMethod: 'HMAC-SHA1',
     _nonceSize: 32,
     _headers:
      { Accept: '_/_',
        Connection: 'close',
        'User-Agent': 'Node authentication' },
     _defaultClientOptions:
      { requestTokenHttpMethod: 'POST',
        accessTokenHttpMethod: 'POST' },
     _clientOptions:
      { requestTokenHttpMethod: 'POST',
        accessTokenHttpMethod: 'POST' } } }

And this is error i have:

{ statusCode: 400,
  data: '{"error": "This app does not have permission for this operation."}' }
{ lastAccess: 1329144199932,
  cookie:
   { path: '/',
     httpOnly: true,
     _expires: Mon, 13 Feb 2012 18:43:19 GMT,
     originalMaxAge: 14400000 }

How to fixed problem, please help me
i already get newest dropbox-node

**Comment by evnm** [comment]
Is it possible that you're using an old consumer key pair? According to [this](http://forums.dropbox.com/topic.php?id=47214) this error can occur if your key predates the era of Dropbox's OAuth-only API.

**Comment by thienit5** [comment]
Thanks alot for your help,  i've just created my app, so app key is new.
but i'm worry about: i use account login dropbox (mail/pass) to connect, it's right ? or i must use user test to test my app?

I can't add users (five user) to test
The program show: Test your app with up to five users   No users accessing this app
This is one of my development apps where I haven't enabled extra users yet: http://dl.dropbox.com/u/340607/enable_extra_users.png

This is one of my development apps where I have enabled extra users: http://dl.dropbox.com/u/340607/extra_users_enabled.png

How is what you're seeing different?

**Comment by evnm** [comment]
The db-browser example app accepts a consumer key/secret pair via the command line and then the web page prompts you for your Dropbox login credentials. The additional users feature shouldn't matter for the db-browser example app, as you can simply connect to your own Dropbox as the app's sole user.

**Comment by addamh** [comment]
+1 -- having the same issue. would love to use the library if I can get over this hurdle

**Comment by evnm** [comment]
This library has been deprecated in favor of the Dropbox's official JavaScript lib: https://github.com/dropbox/dropbox-js
