### ISSUE TITLE
putFile should not use blocking I/O to read the file

### ISSUE THREAD

**Issue by thiloplanz** [evnm/dropbox-node#3]
Right now, putFile uses readFileSync which will block the whole system.

```
   file_contents = require('fs').readFileSync(file);
```

Since the REST API call after this is already asynchronous, there will be no changes in the API for putFile (it already accepts a callback).

**Comment by evnm** [comment]
[Fixed](https://github.com/evnm/dropbox-node/commit/7f48bff). Thanks!

**Comment by thiloplanz** [comment]
Wow, that was fast.  You need a flattr button here...
