### ISSUE TITLE
Rewrite getFile to use streams

### ISSUE THREAD

**Issue by evnm** [evnm/dropbox-node#4]
More node-ish and will improve memory usage for large files.

**Comment by sreuter** [comment]
Thanks for adding this :-) Right now, I only sync files  < 5MB  ... :-)

**Comment by evnm** [comment]
I'm not sure yet how this would work. I'm querying the Dropbox API through ciaranj's OAuth lib, which doesn't support streams. Will have to think about this and tinker.

**Comment by sreuter** [comment]
Oh yes, I recognized this dependency as well as I wanted to add "rough" streaming support myself :-)

**Comment by sreuter** [comment]
unscene's node-oauth could be an option at first look, as it "transparently" extends the builtin http client and preserves the ability of streaming...

**Comment by evnm** [comment]
Interesting... I'll look into it. Worse case, we could go with a one-off solution using a different OAuth approach for getFile, at least for the time being.

**Comment by sreuter** [comment]
As long as we can throw in the already received token+secret of the user, i would say yes :-)

**Comment by thiloplanz** [comment]
This would be an excellent improvement. Also for `putFile`, please. (Does OAuth require the whole file / POST body to be signed, or just URL and headers?)

**Comment by ghost** [comment]
Yes, we can't wait to finally enable dropbox sync support in our little pet project :-)

**Comment by evnm** [comment]
As an update, it looks like this is technically feasible in terms of the Dropbox API, by making use of the Content-Range HTTP header. Must investigate whether this would be doable with node-oauth, as we may run into [the same problem as the dropbox gem](https://github.com/RISCfuture/dropbox/blob/master/lib/dropbox/api.rb#L76).

**Comment by thiloplanz** [comment]
The Content-Range header is about splitting a single HTTP request into multiple smaller ones. That would probably be good at some time too, for resumable downloads of huge files, but I think the current issue is more about avoiding to load the complete file into memory, but rather to stream a (single, unsplit) request directly to a file or other sink, copying only a small buffer into memory each time.

**Comment by evnm** [comment]
Derp. I didn't look deep enough into node-oauth's capabilities. It has decent support for performing streaming operations, ala [the last paragraph and code snippet of this example](https://github.com/ciaranj/node-oauth/wiki/Interacting-with-Twitter).

The path I'm currently going down is having a standalone method called `getFileStreaming` or something that returns a request object instead of taking a callback. You then treat this request as a standard EventEmitter thusly:

```
var req = dropbox.getFileStreaming("Public/IMAG0203.jpg")
  , output_stream = require('fs').createWriteStream("out.jpg");

req.on('response', function (res) {
  res.on('data', function (chunk) { output_stream.write(chunk); });
  res.on('end', function () { output_stream.end(); });
});
req.end();
```

Check out [this branch](https://github.com/evnm/dropbox-node/tree/streaming) for the specifics.
