### ISSUE TITLE
add setAccessToken (as an alternative to passing it to every method)

### ISSUE THREAD

**Issue by thiloplanz** [evnm/dropbox-node#6]
> Each API method (except getAccessToken) can take as optional arguments an access token and an access token secret as strings. This is the one way to get around having to call getAccessToken in cases where a valid key pair is known.

It would be nice if there was a method `setAccessToken(token, secret)` which would set the access tokens to be used by method calls when these optional parameters are not present.

Alternatively, this could also be optional third and fourth parameters to the constructor:

```
   var dropbox = 
       new DropboxClient(consumer_key, consumer_secret, token, secret)
```

(By looking at the source, this can currently also be achieved by setting `dropbox.access_token` and `dropbox.access_token_secret`)

**Comment by evnm** [comment]
Going the optional ctor parameter route. Added in [8c04f07](https://github.com/evnm/dropbox-node/commit/8c04f07).

TODO: Update the README.
