### ISSUE TITLE
Fetching binary data doesn't seem to work

### ISSUE THREAD

**Issue by evnm** [evnm/dropbox-node#9]
Pulling down binary data (e.g. images) from Dropbox doesn't seem to be handled properly. When the blobs returned from `getFile` or `getThumbnail` are written to disk as jpg's, they are corrupted.

Looked into passing the strings returned from Dropbox into Buffers using binary encoding, but this didn't solve the problem outright.

**Comment by evnm** [comment]
The root issue of this seems to be the fact that node-oauth [defaults GETs to utf8](https://github.com/ciaranj/node-oauth/blob/master/lib/oauth.js#L306).

**Comment by jtsao22** [comment]
So, is there any solution available or will this require hacking into node-oauth?

**Comment by evnm** [comment]
@ciaranj has been totally unresponsive on this, so I'm assuming it'll require node-oauth surgery.

**Comment by ciaranj** [comment]
eh?   tbh I hadn't noticed it as an issue on github!

**Comment by evnm** [comment]
No worries. @ralphholzmann filed [this issue](https://github.com/ciaranj/node-oauth/issues/30) a while back and then we kinda forgot about it.

**Comment by ciaranj** [comment]
As a work around, instead of passing a callback function to to the node-oauth get , it will return a request object that you can configure whatever encoding you wish on when you add a response handler to it .. would that not help ?

**Comment by jtsao22** [comment]
Thanks guys for responding so quickly! Claranj, that sounds great to me. I just tried dropbox-node w/the setEncoding('utf-8') changed to setEncoding('binary') and got a file that was not corrupted from dropbox, so for sure adding the request object to configure the encoding would be great.

**Comment by evnm** [comment]
Closing this issue, as this library has long been deprecated.
